### ISSUE TITLE
image resizing

### ISSUE THREAD

**Issue by micklegf** [Avinash793/panoramic-image-stitching#9]
in stitch.py you have resized images to size 400. why this number and how can I know the real number for my application?
by default size(400) Panorama_image is sometimes corrupted.

**Comment by 8410ttt** [comment]
I also have this problem,did you solve it?

**Comment by Avinash793** [comment]
@micklegf @8410ttt You need to provide images whose width and height should be at least 400 so that we can resize all input images to have same aspect ratio. This is required during for algorithm to work.

You can check info of your images to get its height or width info.
